trigger:
  branches:
    include:
    - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  application: AzFn.IoTHubOutput

steps:
- template: steps/build.yaml
- template: steps/publish.yaml
